services:
  database:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_template_1
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  db-data: