
name: Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  REGISTRY: "cr.selcloud.ru/docker-star"
  IMAGE_NAME: "crud-server"
  CONTAINER_NAME: "crud-server-container"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:

      # Проверка кода из репозитория
      - name: Checkout main
        uses: actions/checkout@v4

      # Шаг 3: Установить Make
      - name: Install Make
        run: sudo apt-get install make

      # Шаг 4: Выполнить команду из Makefile (например, get-deps)
      - name: Install dependencies via Makefile
        run: make get-deps

      # Шаг 5: Запуск линтера (применимо, если в Makefile есть такая команда)
      - name: Run linter
        run: make lint

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Логин в Docker Registry
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}" $REGISTRY

      # Сборка Docker-образа
      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-build

    steps:
      # Stopping the current containers on the server
      - name: Stop containers on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker compose down

      # Update docker-compose.yml
      - name: Update docker-compose image tag
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          sed -i "/app:/,/image:/s|image: .*|image: ${REGISTRY}/${IMAGE_NAME}:${TAG_NAME}|" docker-compose.yml

      # Copying new files to the server
      - name: Copy updated files to server
        uses: appleboy/scp-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ".env docker-compose.yml"
          target: "/root/"

      # Deploy to Server
      - name: Deploy to Selectel cloud via SSH action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME,REGISTRY,CONTAINER_NAME,$GITHUB_SHA
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            
            # Login into Selectel Registry
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}" $REGISTRY
            
            # Updating the image
            docker pull $REGISTRY/$IMAGE_NAME:$TAG_NAME
            
            # Launching containers with a new build
            docker compose up -d
              


